### ISSUE TITLE
xs throws GeneratorFunction.__proto__ was not Function.prototype.constructor

### ISSUE THREAD

**Issue by dckc** [Agoric/SES-shim#102]
Does this mean xs is non-conforming? Or just that it's not a platform that this code knows about?

https://github.com/Agoric/harden/blob/0a5185ee224b98e75623a2f88143d118e0849eaa/src/anonIntrinsics.js#L230

for reference, my main.js:

```js
import harden from '@agoric/harden';

export default function main() {
  trace("hi there\n");
  const h = harden({});
  trace("harded:", String(h), "\n");
}
```

and my manifest.json:

```json
{
  "include": [
    "$(MODDABLE)/examples/manifest_base.json",
  ],
  "modules": {
    "*": [
      "./main",
    ],
    "@agoric/make-hardener": "./node_modules/@agoric/make-hardener/index",
    "@agoric/harden": "./node_modules/@agoric/harden/dist/harden.esm",
  },
}
```

**Comment by jfparadis** [comment]
This issue has been resolved in SES 2.0, the code doing the collection of intrinsics assumed that it ran in JS, not in SES.

```
GeneratorFunction.__proto__ was not Function.prototype.constructor`
```

The check now works in both modes (JS and SES) because don't check against Function, which can be tamed, but against  Function.prototype.constructor which has a different value in SES and in JS.
