### ISSUE TITLE
Some issues with unpkg 0.7.0

### ISSUE THREAD

**Issue by GrandSchtroumpf** [Agoric/SES-shim#208]
Hello,
Since version 0.7.0 when importing with `<script src="https://unpkg.com/ses"></script>` the link redirect to `https://unpkg.com/ses@0.7.0/src/lockdown-shim.js` which doesn't exist instead of `https://unpkg.com/ses@0.7.0/dist/ses.umd.js`.

Also the global object is called `lockdown` and has only one key `lockdown`, which is not super readable : 
```javascript
lockdown.lockdown()
const c = new Compartment({ ... });
```

Thanks for this great library :)

**Comment by kriskowal** [comment]
I’ll have a fix for this in 0.7.1 shortly. It looks like your answer for #210 is that we should continue publishing with a UMD build. Thank you!

**Comment by kriskowal** [comment]
@GrandSchtroumpf Does your comment about the `lockdown.lockdown()` name also apply to the previous version?

**Comment by kriskowal** [comment]
Evidently it does not:

https://unpkg.com/ses@0.6.0/dist/ses.umd.js reads `SES.lockdown()`.

**Comment by kriskowal** [comment]
Looks like we renamed `SES` to `lockdown` at https://github.com/Agoric/SES-shim/commit/b23269e44d5a03b98d1c1fdad0d6dabe05ceb3b2#diff-f46451287334bf92ba633dd5d86ecddc

@warner @erights Do you know whether this was intentional? This is the name folks see only if they’re using SES as a UMD script bundle.

**Comment by erights** [comment]
Hi @jfparadis, What did you intend?

@kriskowal, What are the implications for non-UMD users?

**Comment by kriskowal** [comment]
@erights, there are no implications for non-UMD users. The rollup.config specifically designates the name of global field to carry the exports of the root module it bundles. ESM and CommonJS usage both refer to SES by a module specifier and may destructure lockdown however they wish.

**Comment by warner** [comment]
The API is very different: old-SES exposed a single SES object (default export) with a method named `createSESRootRealm`, whereas new SES exposes a named export `lockdown` that is a function. The arguments `ses.createSESRootRealm()` and `lockdown()` are entirely different.

If downstream usage makes it look like `SES` got renamed to `lockdown`, then something is weird: simply renaming the name into which the module's export is placed is not sufficient to migrate to the new version.

**Comment by warner** [comment]
Ah. Ok, that does sound like the UMD bundle should be using `ses` (in particular `ses.lockdown()`) rather than pretending the name of the whole package is `lockdown`.

I don't know that we've looked too carefully at the UMD case. I know none of the Agoric code is using that flavor: the challenge page uses CJS, everything else uses ESM.

**Comment by kriskowal** [comment]
Version 0.7.1 is tagged and released. The UMD is up and it exports `ses.lockdown()`. The API has changed since the 0.6 train.

https://unpkg.com/ses@0.7.1/dist/ses.umd.js

unpkg.com redirects ses@0.7.1 to src/lockdown-shim.js still, which is the ESM module, which is now published appropriately. I believe this is the behavior we desire. Please feel free to reopen if this isn’t a sufficient resolution.

**Comment by GrandSchtroumpf** [comment]
Thanks all for the quick answers & solution. Personaly I'm fine with that. But I'm not sure to understand why you want unpkg to redirect to the ESM module. How should this be used ?
I've tried:
```html
<script src="https://unpkg.com/ses" type="module"></script>
```
And : 
```html
<script type="module">
  import { lockdown } from 'https://unpkg.com/ses'
<script>
```
but both gave me this error: 
`Uncaught TypeError: Failed to resolve module specifier "@agoric/make-hardener". Relative references must start with either "/", "./", or "../".`

**Comment by kriskowal** [comment]
@GrandSchtroumpf The change proposed in #217 may address this issue. We’re making the CommonJS bundle default, and using the new Node.js conditional exports map to override main only for Node.js with ESM support.
