### ISSUE TITLE
expose Compartment shim too

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#224]
To write the `SES-adapter` package (#216), I need access to the `Compartment` constructor outside of a SES environment. I haven't tested it yet, but I think it might be sufficient to have `SES` expose the `Compartment` class next to `lockdown`. If you use this `Compartment`, it won't be secure like the global you'd get after calling `lockdown`, but I'm hoping it would still be enough for `SES-adapter`'s purposes.

```js
import { lockdown, Compartment } from 'ses';
```

Another alternative would be to rearrange this monorepo, moving `packages/ses/src/compartment-shim.js` back into a resurrected `packages/compartment-shim/`.

@kriskowal @michaelfig @erights any thoughts about the differences? Do you think `new Compartment()` using `compartment-shim` (but not `lockdown()`) would give us the good-enough-for-unit-tests vesion that we want for `SES-adapter`?

**Comment by erights** [comment]
I think exposing `Compartment` outside of SES, with no change in the semantics of `Compartment` itself, is now actually necessary for the SES proposal to advance in committee anyway. This is because the agreed division of responsibility between the Realms proposal and the SES proposal depends on `Compartment` providing all host hooks, some of which are needed for some uses of the `Realm` API.

My knowledge of the current SES-shim implementation as well as the issues in integrating `make-importer` into `Compartment`, is currently too stale to make the following statement with confidence:

AFAICT, exposing `Compartment` this way should not need any more mechanism than our previous plans. It should only require a modest rearrangement of the mechanisms we'd build anyway. If there is any overall difference in complexity, I'd expect this new way to be simpler.

**Comment by warner** [comment]
I don't know if this is the approach we want to use, but if so, #225 might be the way to implement it.

**Comment by warner** [comment]
FYI, I'm no longer trying to make `Compartment` work outside of SES, so I no longer need this to be exposed separately. I'll leave it open because it sounds like we need it for the spec process.

**Comment by kriskowal** [comment]
`Compartment` is now provided by `ses` as a global and is orthogonal to `lockdown`. Lockdown “tames” Compartment in a fashion spiritually similar to other evaluators and is powerful before lockdown.
