### ISSUE TITLE
Start Compartment retains original global Function after lockdown

### ISSUE THREAD

**Issue by kriskowal** [Agoric/SES-shim#273]
SES has a somewhat relaxed stance on what may be done in a realm’s “start compartment”, but not so relaxed that the original `Function` constructor should be left untamed.

```js
import { lockdown } from 'ses';
const f = Function;
lockdown();
console.log(Function === f);
// true, should be false

const c = new Compartment();
console.log(c.evaluate('Function') == f);
// false
```

**Comment by erights** [comment]
Also presumably the original global `eval` function. This is insecure not because of scope, since their global scope is the genuine global, which is not the global of the start compartment.
It is insecure because it allows sloppy mode. If pre-lockdown code did nothing special to preserve the possibility of sloppy, then post lockdown code, even running in the start compartment, should be unable to introduce sloppy mode

**Comment by kriskowal** [comment]
Lockdown now tames Function in the start compartment.

```js
import "./ses.js";
const f = Function;
lockdown();
console.log(f === Function); // false
```
