### ISSUE TITLE
Reevaluate the dependency on Babel

### ISSUE THREAD

**Issue by jfparadis** [Agoric/SES-shim#39]
Currently, the module transform depends on Babel, but requires a very small subset of Babel.

Just like the `esm` package relied on a merged subset of acorn:
https://github.com/standard-things/esm/tree/master/src/acorn

...it would be possible to create a transform that uses a carefully vetted subset of acorn (or another parser) that can be reviewed. @SMotaal has also some great ideas on a simple parser.

@erights  FYI

**Comment by SMotaal** [comment]
@jfparadis I really think the all my experimental effort phase does in fact lead to the conclusion…

Safe parsing, it is parsing which developers can reason about and maintain swiftly. Most "compiling" transpilers other than TypeScript seem to prefer the plugin model, creating exponential drag and dissonance. TypeScript's way whatever that was meant to be has largely discouraged people from adding exponential fuzz, maintenance issues there are purely due to their poor and offensive attitudes to maintenance of user issues — in short, they offer no insights aside from the instability factor of the plugins architecture.

Takeaways from Last Year's efforts:

1. Arrow functions and template literals inspired by https://github.com/erights/quasiParserGenerator.
   - Next step is to refine the actual design which done best with 2+ human persons to avoid unilateral biases, at least fair to say a more typical point of view if I am being honest.

2. Constructs which can abstract nicely the simplicity of Tim Disney's fat tokens (he called it something different I suppose).
   - Next step is to implement those which depends on 1.

> **Recap** — I guess this is kind of saying, I know what I do well, I know what I do somehow to get it out of my way, which only becomes a problem for others, if that is fair to say 😉

**Comment by kriskowal** [comment]
We’ve recently separated `ses/lockdown` from `ses`, such that the former is sufficient if the user only needs `lockdown` and `harden`. This will likely grow to include `Compartment.evaluate` and remain lean (around 32KB). The `ses` module will continue to entrain `babel`, albeit `@agoric/babel-standalone`, and results in about 3MB of payload.

Production uses need `ses/lockdown` with `Compartment.evaluate`, but for XS and Web, we will be investigating tooling that captures the module graph and all modules boiled down to programs passable to `Compartment.evaluate` and the necessary harnesses to link them. This should result in a lean runtime for both of these cases. See #400 #412 #413

For development, the 3MB Babel payload should be acceptable, though obviously using a compiler framework more attuned to client-side use like Acorn would be attractive.

I will close this issue for now to keep our backlog manageable, but please do feel free to continue discussion and even to reopen the issue for reassessment.
