### ISSUE TITLE
SES lite

### ISSUE THREAD

**Issue by kriskowal** [Agoric/SES-shim#412]
#406 created a thin `ses/lockdown` layer that includes only `lockdown` and `harden`. To be a sufficient runtime for archived precompiled applications, it will need at least `Compartment` with `evaluate` in that thin layer. The full `ses` will entrain a JavaScript parser framework so it can faithfully emulate `Compartment` with `import`.

**Comment by erights** [comment]
Since this precompilation will happen by separate untrusted compilers outside of SES, we need to carefully explain what threat models we do and do not protect against in the face of buggy or malicious translations. The remaining protections are impressively strong and useful, but explaining it will take some work.

**Comment by erights** [comment]
@kriskowal how done is this? Can we close this issue?

**Comment by dckc** [comment]
Sound's a lot like what we're using on xsnap. It's done to my satisfaction.
