### ISSUE TITLE
Circular dependency between transform-module and make-importer

### ISSUE THREAD

**Issue by jfparadis** [Agoric/SES-shim#49]
Tests in transform-module depend on make-importer and vice versa. This means both packages must to evolve at the same time to avoid breaking changes, not only in development but in the installations.

For example, if make-imported is changed on the blockchain aka server, all code will cease to work until re-transformed. All clients need to evolve at the same time to keep submitting code.

The addition of version should allow the output of transform-module to evolve independently of make-importer. But just as importantly, make transform-module should test its own output, and not depend on one of its consumer for validation. The tests should follow clearly defined and guarded specs that make-importer.

Otherwise, the two repos act as one giant repo: it's impossible to introduce breaking changes in transform-module without at the same time producing a make-importer able to test it.

**Comment by kriskowal** [comment]
`make-importer` is in an ephemeral state and this issue is not likely to come to bear. My intention is to either delete or recreate make-importer by refactoring out the compartment module loader internals of `ses`. Significantly, this includes a copy of `module-instance.js` that originated in `make-importer`.
