### ISSUE TITLE
harden, lockdown on XS

### ISSUE THREAD

**Issue by dckc** [Agoric/SES-shim#507]
@erights says: Are we no longer blocked on harden-related issues?
@warner says: I think we're past those, but in a hackish way. _(see dealing with `AsyncFunction` with `getAnonIntrinsics` https://github.com/Agoric/agoric-sdk/issues/511#issuecomment-716858983 c206eaa)_ I doubt we're hardening enough to prevent mutable-globals communication channels within a vat (in XS).
@erights: Gotcha. For that, we should be using logic extracted from SES-shim's lockdown

The extent to which this is distinct from #104 is not completely clear to me.

**Comment by erights** [comment]
It is distinct from #104. The thing that `lockdown` does is it gathers all the primordials that need to be hardened together into the `intrinsics` object. Then at 
https://github.com/Agoric/SES-shim/blob/3cf9499317f61511811363f668c37d225984e2b5/packages/ses/src/lockdown-shim.js#L175
it uses harden to harden all the primordials by hardening that root `intrinsics` object. For this purpose, the current `harden` and the simplified `harden` of #104 would work equally well.

This issue is mostly about that gathering into an `intrinsics` object, together with the repairs that need to happen before that hardening.

**Comment by erights** [comment]
An attractive approach that we've talked about, for untangling SES-shim into the parts that should and should not run on XS, it to carefully and fully use the idempotent-only-replace-if-not-present shimming strategy. That way, however much XS provides, we would feature detect that it is present and use it rather than replacing it. Most of this can happen by feature testing for the simple presence or absence of property names or global variable names. Some might involve behavioral tests, though none immediately come to mind.

**Comment by dckc** [comment]
It evidently Just Works now.

That is: `xsnap -s dist/lockdown.umd.js`

I happen to have bytecode tracing on: https://gist.github.com/dckc/ef9c741b8c6f555837882ea49ab75d37

Before I close this, I'd like to understand if it's fixed by some recent change in SES-shim or it worked all along and we were just confused. @erights ? @kriskowal ?

**Comment by dckc** [comment]
I suggest that this is done in #2194 . @kriskowal if you agree, would you please close this? Or re-assign to @erights or @warner or whoever else should judge?

**Comment by kriskowal** [comment]
I think we got it!
